---

- name: Set timezone to
  timezone:
    name: Asia/Kabul

- name: install keyboard-configuration
  become: true
  apt:
    name: keyboard-configuration
    state: present
  when: ansible_os_family == 'Debian'

- name: write keyboard configration
  become: true
  template:
    src: keyboards.j2
    dest: /etc/default/keyboard
    force: true
    owner: root
    group: root
    mode: 'u=rw,go=r'
  notify:
    - dpkg-reconfigure keyboard-configuration
