---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: stretch
    image: debian
    image_version: 9
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: true
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
